.github/actions/setup-python-tools/action.yml
Makefile
containers/Dockerfile.builder
containers/Dockerfile.cpu.base
containers/Dockerfile.cuda.base

New `pip` [version](https://pypi.org/project/pip/25.1/) `25.1` seems to have introduced a regression where `pip-compile` is failing.
Example: https://github.com/Snapchat/GiGL/actions/runs/14714954906/job/41296087148
Locking the pip version allows `pip-compile` to continue to work i.e. https://github.com/Snapchat/GiGL/actions/runs/14714954906/job/41296087498
This is change is currently blocking https://github.com/Snapchat/GiGL/pull/5

Lock pip version to fix broken pip-compiles. 

---

.github/workflows/generate-hashed-requirements.yml
.mdformat.toml
README.md
python/pyproject.toml
requirements/dev_darwin_arm64_requirements_unified.txt
requirements/dev_linux_cpu_requirements_unified.txt
requirements/dev_linux_cuda_requirements_unified.txt
requirements/linux_cpu_requirements_unified.txt
requirements/linux_cuda_requirements_unified.txt

The Component table was broken after OSS migration - this fixes the formatting.
Update: I found out this is due to our recently introduced `mdformat` linter - by default it doesn't consider tables and breaks their formatting by inserting new lines.
As a result, I had to add a mdformat plugin for correctly formatting markfown tables.
Prior:
W/ Fix:

[FIX] GiGL Component Documentation Table

---

python/gigl/distributed/distributed_neighborloader.py
python/tests/unit/distributed/distributed_neighborloader_test.py

This allows us to sample against multiple nodes in the same "batch".
Moving over http:://go/internal-gigl-pull/496

Support batching input in our neighbor loader

---

python/gigl/types/graph.py
python/tests/unit/distributed/distributed_neighborloader_test.py
python/tests/unit/types_tests/graph_test.py

As you've mentioned prior, we should do this eventually - I think this will make our supervised HeteroData -> Data conversion easier.

swap to generating label edge types based on message passing edge types

---

python/gigl/common/data/export.py
python/gigl/common/utils/retry.py
python/tests/unit/common/data/export_test.py

When uploading embeddings to GCS, retry on both GCP errors (e.g., ServiceUnavailable) and connection related errors (e.g., connection aborted).
Unit tested.

Retry on connection errors

---

examples/distributed/homogeneous_inference.py
python/gigl/common/data/export.py
python/tests/integration/common/data/export_test.py
python/tests/unit/common/data/export_test.py

When loading embeddings into BigQuery, return the load job info so that user could add check on it. For example, user could check whether the number of embeddings being loaded is expected.
- Unit tested
- Integration tested

Return BigQuery load job object

---

.github/workflows/release-documentation.yml

Introducing new workflow that will allow us to deploy our docs to github pages.
I have already [merged it to snap-research/GiGL](https://github.com/snap-research/GiGL/actions/runs/14806387587/workflow?pr=21).
You can see the successful results of [deployment](https://github.com/snap-research/GiGL/actions/runs/14806387587/job/41575241673?pr=21) using the rule here: https://snap-research.github.io/GiGL/

Create workflow for releasing documentation

---

python/gigl/distributed/distributed_neighborloader.py

As discussed offline, if we don't do this then we can get extra messages error messages if we throw during __init__ which is confusing.

Set _shutdowned right away

---

python/gigl/distributed/constants.py

Hopefully we this can prevent us from running into the issues where we see port 30000 is taken on the cloudbuild machines

bump port numbers up - try to deflake tests

---

python/gigl/common/data/export.py
python/tests/integration/common/data/export_test.py
python/tests/unit/common/data/export_test.py

- Updates `load_embeddings_from_bigquery` to have asynchronous support so that we aren't blocking on BQ finishing
We want this for heterogeneous inference so that we can begin the inference process for the next node type without requiring this step to be finished for the previous inference node type. See [here](https://github.com/Snapchat/GiGL/pull/20#discussion_r2082618610) for more context.

Update `load_embeddings_from_bigquery` to run asynchronously

---

python/gigl/common/data/load_torch_tensors.py
python/gigl/distributed/dataset_factory.py
python/gigl/distributed/dist_partitioner.py
python/gigl/distributed/dist_range_partitioner.py
python/gigl/distributed/distributed_neighborloader.py

Changes to improve the performance of range-based partitioning and TFRecord Dataloading
- Restructure `_partition_by_single_chunk` in partitioner so that the rank indices are only sent to RPC if we are generating a partition book, reducing RPC communication load
- Slight restructure of range-based partitioning to make cleanup happen earlier
- Delete reference to `input_data` so that its assets are cleaned up as well through reduced reference count
- Change `process_start_gap_seconds` in the neighbor loader to be float instead of int type, conforming better to params for `init_neighbor_loader_worker`
- Change dataset factory to pass `node_tf_dataset_options` and `edge_tf_dataset_options`, rather than just one singular `tf_dataset_options`. This is important to tune …

Improve Range Based Partitioning

---

python/tests/unit/distributed/distributed_neighborloader_test.py

We are seeing fairly consistent unit test failures due to the hard-coded ports. While I am working on a solution to enable dynamic port inference, we disable these tests here to enable other PRs to be landed swiftly in the meantime.

Disable NeighborLoader tests until ports are dynamically allocated

---

Makefile
scripts/create_dev_instance.py

Context:
I am overhauling the Getting Starting Guide of which totality of changes are introduced here: https://github.com/Snapchat/GiGL/pull/53
Since that draft is too big, I am breaking it down into a few different PRs.
This PR introduces script that allows one to create a new dev instance.
One can run this script with args:
```bash
python scripts/create_dev_instance.py \    
--project="" \
--zone="us-central1-c" \
--service_account="SA@PROJECT_NAME.iam.gserviceaccount.com" \
...
...
```
Alternatively, one can directly run this script in interactive mode:
```bash
python scripts/create_dev_instance.py
```
***Ready for code review?:*** …

Introduce create dev instance script

---

python/gigl/distributed/dataset_factory.py
python/gigl/types/graph.py
python/gigl/utils/data_splitters.py
python/tests/integration/distributed/distributed_dataset_test.py
python/tests/unit/distributed/distributed_dataset_test.py
python/tests/unit/distributed/distributed_neighborloader_test.py
python/tests/unit/types_tests/graph_test.py
python/tests/unit/utils/data_splitters_test.py

Updated the split API and functionality in GiGL.
- Moves `should_convert_labels_to_edge` to the splitter class and make `supervision_edge_types` param more explicit
- Update SSL building logic to infer edge types based on the supervision edges, rather than all edges
- Update `treat_labels_as_edges` to correctly handle labeled edges in both "in" and "out" edge directions
- Update corresponding tests

Update GiGL Splitter

---

CODEOWNERS

As discussed offline, since this file get's modified when we build new docker images, it may be useful for all of us to be able to edit it.

Allow all devs to approve changes to run_command_on_active_checkout.yaml

---

python/gigl/utils/data_splitters.py
python/tests/unit/utils/data_splitters_test.py

Instead of https://github.com/Snapchat/GiGL/pull/78 let's go with this approach.
Now, if there isa. positive node id with no corresponding hard negative labels, the nodes negative labels will be padded with our padding node, which is later stripped out.

Allow for non-existant anchor node ids when creating labels

---

python/gigl/distributed/dataset_factory.py
python/tests/unit/distributed/dataset_factory_test.py

If we don't do this, then we will use the provided supervision edge type, something like `paper-cites-paper`, which is not what the rest of our code expect.

Use DEFAULT_HOMOGENEOUS_EDGE_TYPE as supervision edge type for homogeneous graphs

---

python/gigl/distributed/__init__.py
python/gigl/distributed/utils/__init__.py
python/gigl/distributed/utils/networking.py
python/tests/unit/distributed/utils/networking_test.py

Introducing utility functions to get free ports.
Specifically, introduced `gigl.distributed.utils.get_free_ports_from_master_node()` which helps  get free ports from master node, that can be used for communication between workers. This will help reduce situations where certain nodes are already taken.

Introduce utility to fetch free ports from master node rank zero

---

python/gigl/orchestration/kubeflow/runner.py

If we provide these like: `--task_config_uri= /foo/bar/file.yaml` they will get passed in as an empty string, which is not what we want!
This can happen from our [make rule](https://github.com/Snapchat/GiGL/blob/f00d1d290acc9f3abd2dc10a77e9eb69e896c864/Makefile#L433-L445) too.
Maybe we should check that the URI exists but this may not always be possible due to permissions so let's just leave it as "non empty string" for now?
When it fails it looks like:
```
ValueError: Missing values for the following flags for a Action.RUN command: ['task_config_uri']. All required flags are: ['resource_config_uri', 'task_config_uri', 'container_image_cpu', 'container_image_cuda', 'container_image_dataflow'].
```

Require non-empty flags be provided

---

python/tests/unit/distributed/dataset_factory_test.py

Originally, I wanted to test against a heterogeneous dataset too, but we don't have any one with labels setup, and we don't expose `_ssl_positive_label_percentage` here.
But I added these checks and might as well go for them :P

Test correct node ids are set too

---

scripts/create_dev_instance.py

Added the reservation arg in `create_dev_instance.py` so we can pass in any reservation if needed for creating VMs.

added reservation in vm script

---

.github/actions/run-cloud-run-command-on-active-checkout/action.yml
.github/workflows/on-pr-comment.yml
Makefile

Try to pipe in GIT_BRANCH to cloud build workers, so we can have our e2e pipelines named with the git branch.
e.g. https://console.cloud.google.com/vertex-ai/pipelines/locations/us-central1/runs/cora-glt-udl-test-on--04698?inv=1&invt=Ab0dkw&project=external-snap-ci-github-gigl will have the branch name in it.
Tested that the make file changes work locally. 
I cannot test the gh action changes easily locally so let's "test on main".
If the integration tests start failing let's roll this back immediately. 

Tag E2E integration test pipelines with git branch

---

.github/actions/run-cloud-run-command-on-active-checkout/action.yml
Makefile

https://github.com/Snapchat/GiGL/pull/100 broke our e2e tests, whoops. See https://github.com/Snapchat/GiGL/actions/runs/15743367245/job/44374020081 for a test that broke. 
`--set-build-env-vars` is not a valid flag for `gcloud builds submit`.
Will send out a follow up PR where I make the change from `--substitutions=_CMD="${{ inputs.cmd }}"` to `--substitutions=_CMD="${{ GIT_HASH=$(git rev-parse HEAD) inputs.cmd }}"`

Rollback breaking change breaking e2e tests

---

python/gigl/distributed/dataset_factory.py
python/gigl/utils/data_splitters.py
python/tests/test_assets/distributed/utils.py
python/tests/unit/distributed/distributed_neighborloader_test.py
python/tests/unit/utils/data_splitters_test.py

Changes:
* update _fast_hash to run again to improve mixing - without this our N=20 node ids had splits like [18], [0], [2]
* enforce `val_num` and `test_num` as floats - since we can't guarantee counts easily anymore.
* Update splitting logic to ensure nodes are always selected into the same split [discussed more below].
* Added a (basic) test for the "distributed" case.
* Removed some tests that relied on integer counts.
The issue with our previous splitting logic, is that even though a given node id would always have the same hash on different machines, since we sorted the hashed, it's "position" may be different and so it may be selected into different splits.
For instance, let's assume the hash function is the identity, and `rank_0_nodes: [0, 1, 2, 3] rank_1_nodes: [3, 4, 5, 6]`
On …

Ensure node ids are always selected into the same split

---

python/gigl/utils/data_splitters.py

Without this change, the returned splits would be on CPU, which caused our unit tests to fail (see below) when run on a machine with GPU as we will default to using GPU when available.
```
======================================================================
ERROR: test_ablp_dataloader_1_Positive_edges (distributed.distributed_neighborloader_test.DistributedNeighborLoaderTest)
----------------------------------------------------------------------
Traceback (most recent call last):
File "/opt/conda/envs/.../lib/python3.9/site-packages/parameterized/parameterized.py", line 620, in standalone_func
return func(*(a + p.args), **p.kwargs, **kw)
File "/GiGL/python/tests/unit/distributed/distributed_neighborloader_test.py", line 514, in test_ablp_dataloader
mp.spawn(
File …
```

Ensure returned splits are on the input device

---

python/gigl/common/data/load_torch_tensors.py
python/gigl/distributed/dist_partitioner.py
python/gigl/distributed/utils/serialized_graph_metadata_translator.py
python/tests/unit/distributed/dataset_input_metadata_translator_test.py
python/tests/unit/distributed/distributed_dataset_test.py

PR which patches two items with the translator
- Fix a bug where we weren't loading positive labels if the label's `feature_dim` is set to 0
- Modify code so that an edge type exists which doesn't have a `mainEdgeInfo` field and only a `positiveEdgeInfo`, we still are able to load, partition, and register that label to the dataset

Patch SerializedGraphMetadata Translator

---

examples/distributed/heterogeneous_inference.py
python/gigl/distributed/dataset_factory.py
python/tests/unit/distributed/distributed_dataset_test.py

- Adds back the port as a parameter to the `build_dataset` utility

Add Port as parameter to `build_dataset`

---

python/gigl/distributed/dist_ablp_neighborloader.py

As preparation for our launches we should document the fields we're adding in our ABLP loader.
This change only updates the documentation.
I chose explicitly to not further document num_sampled_nodes and num_sampled_edges as they're GLT details and I'm not sure we should be tying ourself to them, and those fields aren't super relevant to users, whereas the label fields are super important.

Add documentation for y_positive, y_negative

---

.github/actions/run-cloud-run-command-on-active-checkout/action.yml
.github/workflows/on-pr-comment.yml

Two changes in this pr:
1. Increase test timeout for unit tests, we see in e.g. https://console.cloud.google.com/cloud-build/builds/3ffc7864-8ab0-45da-9484-fd082940d9e8?project=external-snap-ci-github-gigl&invt=Ab1QZw&inv=1 that our unit tests may take 37 mins so let's bump again
2. Decrease polling limit for cloud build, to try and prevent errors discussed below.
I've been seeing the below errors for cloud build, which are odd because the jobs can still succeed we just fail cause the polling gets rate limited.
I do think the math here doesn't quite add up, if we're at 900 requests/min, then each job should hit 60/requests/min with 1second polling.
This means we should be able to run 15 jobs at the same time, which translates to 5 concurrent merges, as each merge launches three jobs …

Fix some issues with out CICD tests

---

python/gigl/distributed/dist_ablp_neighborloader.py
python/gigl/distributed/dist_neighbor_sampler.py
python/gigl/distributed/utils/neighborloader.py
python/tests/unit/distributed/distributed_neighborloader_test.py
python/tests/unit/distributed/utils/neighborloader_test.py

Previously, we were including the positive labels which we fanout from in the `batch` and `batch_size` fields of the returned Data/HeteroData object. We should instead make it so that only the anchor nodes are included in this field. Additionally, the `batch_size` field was not being set previously when we convert a HeteroData object to a Data object.
- Added fix for above issues
- Add tests for above issues
- Some readability improvements to some variable naming

Fix ABLP_loader setting of `batch` and `batch_size`

---

examples/MAG240M/fetch_data.ipynb
examples/MAG240M/mag240m.ipynb
examples/toy_visual_example/toy_example_walkthrough.ipynb

A comment was brought up when we added the notebook examples to our repo to include a self link to the notebook so folks viewing the rendering from the doc website have easy access to it.
Currently, the doc website renders rich HTML, with no obvious way to directly navigate to the underlying notebook.
i.e.https://snapchat.github.io/GiGL/examples/toy_visual_example/toy_example_walkthrough.html

Add self link in notebooks

---

python/gigl/src/data_preprocessor/lib/enumerate/utils.py

Enumerate all node data references or all edge data references in parallel.
Currently the parallelism is limited by the number of CPU(s) on the host machine. Since the enumeration jobs are BigQuery jobs, and the host machine only needs to launch job and then listen to job status, it is not computation intensive and is safe to run more jobs in parallel.
Tested run pipelines and verified that all enumeration jobs were launched in parallel.

Run all node or edge enumeration BigQuery jobs in parallel

---

python/gigl/src/common/constants/training.py

Doing this so that we can correctly infer the types downstream. 
Prior to this change mypy saw this as a `builtins.dict[builtins.str, builtins.function]` which somehow would make `LinkPredictionDecoder` [`1] unhappy because it wants a `Callable`, not a `function`, whatever the difference there actually is.
[1]: https://github.com/Snapchat/GiGL/blob/kmonte/type-act/python/gigl/src/common/models/layers/decoder.py#L24-L25

Type ACT_MAP

---

python/gigl/common/services/vertex_ai.py

Some ongoing efforts require training workers to have ample disk space such that local model checkpoints / assets can be saved.  Current VAI job config doesn't support this, hence this change. We can't flexibly specify this resource in configs today, hence making the change here.

Enable specifying larger disks for vai training

---

python/gigl/distributed/dist_ablp_neighborloader.py
python/gigl/distributed/distributed_neighborloader.py
python/gigl/distributed/utils/neighborloader.py
python/tests/unit/distributed/distributed_neighborloader_test.py
python/tests/unit/distributed/utils/neighborloader_test.py

- In the case where num_neighbors is a dict, we were previously checking if the edge types of the dataset is equal to the edge types of num_neighbors **before** patching it with the positive label edge types, resulting in failure. This order should be switched, which is patched in this PR
- Additionally, we don't call patching if dataset.get_edge_types() is None, indicating a homogeneous dataset.
- Also restructures the ABLPNeighborLoader and DistNeighborLoader to be more similar in the order where they patch fanout.
- Update `patch_subgraph_from_fanout` to not infer fanout for non-label edge types if provided fanout is a dictionary
- Update tests for `patch_subgraph_from_fanout` utility
Did you add automated tests …

Fix Fanout in Dataloaders

---

examples/link_prediction/heterogeneous_inference.py
examples/link_prediction/homogeneous_inference.py
python/gigl/distributed/dist_ablp_neighborloader.py
python/gigl/distributed/distributed_neighborloader.py
python/gigl/distributed/utils/init_neighbor_loader_worker.py

- Previously, we were calling `init_worker_group` once per dataloader, even in the case of trainer where we have multiple dataloaders. We should only need to call this once since the resulting `GLT.DistContext` is the same regardless of which dataloader is calling it on each machine, and update this code accordingly.
- Similarly, we were previously calling `init_rpc` inside of the dataloaders so that we could call `barrier()` in the inference loop. We should not be calling this `init_rpc` more times than necessary. Additionally, we no longer need this `init_rpc` call, since we are now using `torch.distributed.init_process_group` as part of both inference and training, and can use that instead to set up barriers at different points of the training/inference loop. The …

Remove unnecessary distributed calls in Dataloader setup

---

.dockerignore
.github/actions/commit-and-push/action.yml
.gitignore

Needed for: https://github.com/Snapchat/GiGL/pull/141
Providing ability for the `commit-and-push` action to have a new param `to_new_branch_named` specific.
If specific, it will push the changes to this new branch.
This was tested on the following branch: https://github.com/Snapchat/GiGL/pull/141
w/ resulting branch push here: https://github.com/Snapchat/GiGL/pull/150

Add ability to push to a new branch in `commit-and-push` github action

---

examples/link_prediction/heterogeneous_inference.py
examples/link_prediction/homogeneous_inference.py
python/gigl/distributed/dist_ablp_neighborloader.py
python/gigl/distributed/distributed_neighborloader.py
python/gigl/distributed/utils/init_neighbor_loader_worker.py

This reverts commit 460a82910b4c913a0698ea02198c117df6202638.
This breaks some internal pipelines which still rely on `glt.distributed.barrier`
Let's rollback and forward later with more fixes :)
cc: @mkolodner-sc

Revert "Remove unnecessary distributed calls in Dataloader setup (#140)"

---

python/gigl/common/data/export.py
python/gigl/src/common/utils/file_loader.py
python/tests/integration/common/file_loader_test.py
python/tests/unit/common/data/export_test.py

Enable `EmbeddingExporter` to take in any type of URI for exporting to.
Doing this so our KDD walkthrough minimally requires GCP.
Also made the unit tests have a lot less mocks now that we can test against local files :)
The GCS path should still be tested in `python/tests/integration/common/data/export_test.py`.
Note that `load_embeddings_to_bigquery` requires a GCS uri so we can't migrate that, so we can just dump to dataframe or something for our examples.

Allow EmbeddingExporter to export locally

---

testing/README.md
testing/notebooks_test.py

I recently added `testing/notebooks_test.py` as a way to ensure our notebooks are actually working.
Since the tutorial is important, we should also test it :P
You can run these tests with `/notebook_tests` as a comment

Add tutorial notebook to our test suite

---

python/gigl/src/common/utils/dataflow.py

Dataflow jobs can sometimes run indefinitely due to some issues, this guards against it by adding a shorter max TTL on jobs.
Ran a [manual test](https://console.cloud.google.com/dataflow/jobs/us-central1/2025-07-17_14_55_28-27828424271130329;mainTab=JOB_METRICS;bottomTab=JOB_LOGS;expandBottomPanel=true;logsSeverity=ERROR;graphView=0?project=external-snap-ci-github-gigl&pageState=(%22dfTime%22:(%22l%22:%22dfJobMaxTime%22))&inv=1&invt=Ab3G5A) w/  `MAX_WORKFLOW_RUNTIME_WALLTIME_SECONDS = 60`
Notably, the job started @ 
July 17, 2025 at 2:55:28 PM PDT
Starting 1 workers in us-central1... @
2025-07-17 14:55:35.053 PDT 
And the job cancelled itself @
2025-07-17 2:59:03.386 …

Add dataflow job timeout

---

python/gigl/src/common/models/pyg/heterogeneous.py
python/tests/unit/module/models_test.py
python/tests/unit/src/common/models/pyg/heterogeneous_test.py

This was a tricky one. When we initialize a HGTConv layer, we provide some edge types, which it uses to create an offset mapping for each edge type. When we forward some `data.edge_index_dict` through this layer, we require that the edge types there have the same order as the edge types in the constructor, otherwise the offsets will be off. For large graphs, this will lead to indexing errors during segmented matrix multiplication [[1](https://pyg-lib.readthedocs.io/en/stable/_modules/pyg_lib/ops.html#segment_matmul)] as such
```
split_with_sizes expects split_sizes have only non-negative entries, but got split_sizes=[66491, -41288, 41288, 66491, 0, 0]
```
which is caused by the `ptr` tensor being in a non-ascending order` 
For smaller graphs, segmented matrix …

Update HGT model to handle differently ordered edge types

---

Makefile
containers/Dockerfile.builder
containers/Dockerfile.cpu.base
containers/Dockerfile.cuda.base
docs/user_guide/getting_started/installation.md
requirements/install_py_deps.sh

Noticed behaviour:
Terms of Service implicitly accepted for conda default channel - even though we don't want to use it.
This forces us not to use it this case. 
Will follow up w/ task where we can just do this at a global level i.e. reliance on `actions/setup-python@v4` which has a pre-installation of conda which uses default channel.

Force conda forge channel only

---

python/gigl/common/utils/gcs.py
python/gigl/src/common/utils/file_loader.py
python/tests/integration/common/file_loader_test.py
python/tests/integration/common/gcs_test.py

* Support copying `GCSURI -> GCSURI` in FileLoader.load_file.
* Added `GcsUtils.copy_gcs_blob` to support this.
* Updated some typing stuff in `FileLoader. load_file` so we can avoid `cast`.
Added tests for both use cases.

support copying from GCS blob to GCS blob

---

examples/tutorial/KDD_2025/heterogeneous_walkthrough.ipynb

Tested this locally, this works.

Swap back to using docker build from scripts/

---

.github/workflows/on-pr-comment.yml
CHANGELOG.md
python/gigl/common/data/dataloaders.py
python/gigl/utils/data_splitters.py
python/tests/unit/utils/data_splitters_test.py

- Adds the NodeAnchorSplitter/HashedNodeAnchorSplitter classes which aims to split node ids instead of edge indices, which the HashedNodeAnchorLinkSplitter is responsible for.
- Re-uses constructs of the HashedNodeLinkSplitter where possible
- Adds relevant tests
This implementation provides additional value over the [GLT splitting implementation](https://github.com/alibaba/graphlearn-for-pytorch/blob/main/graphlearn_torch/python/data/dataset.py#L504-L515) by making less rigorous assumptions about the node ids that are provided to the splitter, such as not requiring every node to be split upon (by requiring as an argument the total number of nodes N and splitting the ids from 0 to N). This may be useful in cases where we may only want to provide a subset of nodes to …

Add HashedNodeSplitter

---

CHANGELOG.md
Makefile
docs/user_guide/config_guides/task_config_guide.md
python/gigl/common/omegaconf_resolvers.py
python/gigl/common/utils/yaml_loader.py
python/tests/unit/common/test_omegaconf_resolvers.py
python/tests/unit/common/utils/yaml_loader_test.py

- Added suport to load arbritary yamls given a dataclass definition
- Added custom Omegaconf resolver for `${git_hash:}`
Both of these will be used here: https://github.com/Snapchat/GiGL/pull/301

Add ability to resolve any yaml --> dataclass using utility + introduce ${git_hash:} resolver

---

examples/link_prediction/heterogeneous_inference.py
examples/link_prediction/homogeneous_inference.py

Doing this is the preferred way as calling del on the loaders does not always clean up all memory, leading to `part or all of the requested memory range is already mapped` errors.

shutdown example inference loaders

---

python/gigl/types/graph.py
python/tests/unit/types_tests/graph_test.py

Do this as a precursor to supporting multiple supervision edge types.
You can review this as a self-contained change (even if the end goal isn't obvious from here :P). Essentially this all goes to supporting https://github.com/Snapchat/GiGL/compare/kmonte/multipler-supervision-edges?expand=1#diff-f135690459bff031aa79fbf2b74e95ff2ed1f389b1f9c6d3fd7e8fe819a64e6bR20-R21 
* Add label_edge_type_to_message_passing_edge_type 

Add label_edge_type_to_message_passing_edge_type

---

python/gigl/src/common/types/pb_wrappers/gbml_config.py
python/gigl/src/config_populator/config_populator.py
python/tests/unit/main.py
python/tests/unit/src/config_populator/config_populator_functionality_test.py

- Adds a GbmlConfigPbWrapper property for skipping embedding path population in the frozen config during `config_populator`
- Adds tests to ensure the embedding path is not populated with this feature flag

Add FeatureFlag for not populating embedding field
