- .github/workflows/on-pr-comment.yml
> Run all integration tests

- python/gigl/distributed/__init__.py
- python/gigl/distributed/dist_link_prediction_data_partitioner.py
- python/gigl/distributed/dist_link_prediction_range_partitioner.py
- python/gigl/types/graph.py
- python/tests/test_assets/distributed/constants.py
- python/tests/unit/distributed/distributed_partitioner_test.py
- python/tests/unit/distributed/load_and_build_dataset_test.py
- Implements the range-based partitioner class and updates corresponding tests
> Implement range-based partitioner

- requirements/install_scala_deps.sh
Again doing this to prevent rate throttling
> host coursier

- Makefile
- scripts/setup_environment.sh
- Update `install_dev_deps` script to also configure docker
> Add docker config to install_dev_deps

- python/gigl/src/common/modeling_task_specs/node_anchor_based_link_prediction_modeling_task_spec.py
- python/gigl/src/common/modeling_task_specs/utils/early_stop.py
- python/tests/unit/distributed/distributed_neighborloader_test.py
- python/tests/unit/src/common/modeling_task_spec_utils/early_stop_test.py
Updates early stop to be:
- Decoupled from the modeling task spec
- Decoupled from checkpointing logic
> Update early stop logic

- CODEOWNERS
> Adding more code owners for .github folder

- .mdformat.toml
- CONTRIBUTING.md
- scala/README.md
- scala/subgraph_sampler/README.md
- scala_spark35/README.md
- scala_spark35/subgraph_sampler/README.md
Prior to this markdown formatter was incorrectly numbering lists.
> Correct sequential numbering in markdown formatter

- .github/cloud_builder/run_command_on_active_checkout.yaml
- dep_vars.env
- mypy.ini
- python/gigl/src/post_process/utils/cosine_similarity.py
- python/pyproject.toml
- requirements/dev_darwin_arm64_requirements_unified.txt
- requirements/dev_linux_cpu_requirements_unified.txt
- requirements/dev_linux_cuda_requirements_unified.txt
It came up that pandas has stubs now so might as well use them.
> type check pandas

- docs/api/index.rst
> Add API Placeholder page

- examples/distributed/configs/e2e_dblp_glt_task_config.yaml
- examples/distributed/heterogeneous_inference.py
- examples/distributed/heterogeneous_training.py
- examples/distributed/homogeneous_inference.py
- examples/distributed/homogeneous_training.py
- examples/models.py
- python/gigl/distributed/dataset_factory.py
- python/gigl/distributed/distributed_neighborloader.py
- Enables Heterogeneous E2E Training on the DBLP dataset using GLT
- Updates the DBLP E2E config
- Small fixes to enable heterogeneous training
> Enable Heterogeneous Training in E2E

- python/gigl/distributed/dataset_factory.py
It was backwards before, whoops!
> Use correct paritioner in build_dataset_from_task_config_uri

- python/gigl/utils/iterator.py
- The log here seems to be polluting our log space significantly during training -- let's remove it.
> Remove log from InfiniteIterator

- .github/actions/setup-python-tools/action.yml
> Goog Auth Action - adding warning

- examples/tutorial/KDD_2025/.gitignore
- examples/tutorial/KDD_2025/heteregeneous_walkthrough.ipynb
- python/gigl/common/data/export.py
- python/tests/unit/common/data/export_test.py
Doing some basic forward pass and embedding exporting here - not sure what else we should be doing since IMO we should be avoiding requiring GCP for this notebook as much as possible.
What we do here is:
1. Instantiate a DistNeighborLoader
2. Go through it and dump the embeddings to disk with `EmbeddingExporter`
3. Read the embeddings from disk and put them in a DF (as a demo).
Notebook runs on my machine :)
> Add some basic "inference" example for our notebooks,.

- docs/user_guide/getting_started/installation.md
I think the instructions were a bit confusing before, this are (IMO) more clear.
> Update local install instructions

- .github/cloud_builder/run_command_on_active_checkout.yaml
- dep_vars.env
- examples/tutorial/KDD_2025/graph_config.yaml
- python/pyproject.toml
> Move matplotlib to deps

- examples/tutorial/KDD_2025/lab_instructions.md
Fix format issue introduced in https://github.com/Snapchat/GiGL/pull/247
> fix format

- examples/tutorial/KDD_2025/README.md
> Update Tut Readme w/ hook and presenter information

- examples/tutorial/KDD_2025/README.md
> Tutorial assets

- CHANGELOG.md
- python/gigl/common/data/dataloaders.py
- Updates the TFRecordDataloader TODO to be more accurate
> Update TFRecordDataLoader TODO

- scripts/create_dev_instance.py
Enabling this as we don't *always* want to have a machine with GPUs.
now users can do `--accelerator_count=0` to not attach any GPU.
Tested this locally and it works :)
> Allow users to specifcy no accelerators when creating dev box

- CODEOWNERS
> Add new code owners

- scripts/create_dev_instance.py
Co-authored-by: Shubham Vij <reachme@shubhamvij.com>
> nit: update error msg - unsupported image

- .cursor/rules/python-patterns.mdc
- .cursor/rules/testing-patterns.mdc
Adding cursor rules see: https://docs.cursor.com/en/context/rules
> Try Adding cursor rules for python dev.

- .github/workflows/on-pr-merge.yml
As discussed offline, let's disable these until they work again.
> disable nb e2e tests on merge

- python/tests/integration/main.py
> Actually use test file pattern

- .github/workflows/fossa-analyze.yml
> Fossa Analyze show logs
